analyzer:
  plugins:
    - custom_lint
  exclude:
    - packages/
    - lib/routes.g.dart
    - lib/theme.dart
  

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false
   
   